In [2]:
import requests
import pandas as pd

In [45]:
def fetch_here(lat, lon, api_key):
    
    url = f'https://discover.search.hereapi.com/v1/discover?at={lat},{lon}&q=restaurant&limit=100&apiKey={api_key}'
    response = requests.get(url)
    
    if response.status_code != 200:
        return ''
    data = response.json()
    
    return data['items']

In [4]:
first_fetch = fetch_here(52.5228, 13.4124,'e8Jr90z14vvM6WedTBedm2Trnv4J_-KLqH4vVllGqqI')

              lat        lng
0       52.338234  13.088346
1       52.339136  13.088346
2       52.340037  13.088346
3       52.340939  13.088346
4       52.341841  13.088346
...           ...        ...
170245  52.671848  13.761117
170246  52.672749  13.761117
170247  52.673651  13.761117
170248  52.674553  13.761117
170249  52.675454  13.761117

[170250 rows x 2 columns]

In [65]:
list_coordinates['lat'][0]

52.338234

In [6]:
to_delete_1 = ['countryCode', 'countryName', 'stateCode', 'state', 'countyCode','county', 'city']
to_delete_2 = ['isOpen', 'structured']

for restaurant in first_fetch:
    
    # delete useless info in the address column

    for item in to_delete_1:
        del restaurant['address'][item]
        
    #delete useless info on the opening times

    #for item in to_delete_2:
      #  del restaurant['openingHours'][0][item]

In [7]:
first_fetch

[{'title': 'Zillestube',
  'id': 'here:pds:place:276u33dc-d167efeb60637e06fec06fbcc058f647',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'Zillestube, Alexanderplatz, 10178 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Alexanderplatz',
   'postalCode': '10178'},
  'position': {'lat': 52.52289, 'lng': 13.41263},
  'access': [{'lat': 52.52335, 'lng': 13.41246}],
  'distance': 19,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True},
   {'id': '300-3000-0000', 'name': 'Sehenswürdigkeit'},
   {'id': '550-5510-0242', 'name': 'Panoramablick'}],
  'references': [{'supplier': {'id': 'tripadvisor'}, 'id': '7346682'},
   {'supplier': {'id': 'tripadvisor'}, 'id': '8779432'}],
  'foodTypes': [{'id': '300-000', 'name': 'Europäisch', 'primary': True},
   {'id': '302-000', 'name': 'Deutsch'}],
  'contacts': [{'phone': [{'value': '+493023890',
      'categories': [{'id': '100-1000-0000'}]},
     {'value': '+493023894636', 'categories': [{'id': '500-5000-0000'}]},
     {'value': '+49493023890'}],
    'www': [{'value': 'http://www.parkinn-berlin.de',
      'categories': [{'id': '500-5000-0000'}]},
     {'value': 'http://www.parkinn-berlin.de/en/panorama-terrace',
      'categories': [{'id': '300-3000-0000'}]},
     {'value': 'http://www.parkinn-berlin.de/restaurant-zille-stube',
      'categories': [{'id': '100-1000-0000'}]}],
    'email': [{'value': 'berlin.hotel@rezidorparkinn.com',
      'categories': [{'id': '500-5000-0000'}]}]}],
  'openingHours': [{'categories': [{'id': '500-5000-0000'}],
    'text': ['Mon-Sun: 17:30 - 23:00'],
    'isOpen': True,
    'structured': [{'start': 'T173000',
      'duration': 'PT05H30M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU'}]},
   {'categories': [{'id': '100-1000-0000'}],
    'text': ['Mon-Sun: 17:30 - 23:15'],
    'isOpen': True,
    'structured': [{'start': 'T173000',
      'duration': 'PT05H45M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU'}]}]},
 {'title': 'Spagos',
  'id': 'here:pds:place:276u33dc-18aba4c72df6433898c7d584dd6eefc3',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'Spagos, Alexanderplatz 7, 10178 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Alexanderplatz',
   'postalCode': '10178',
   'houseNumber': '7'},
  'position': {'lat': 52.52255, 'lng': 13.4128},
  'access': [{'lat': 52.52249, 'lng': 13.41271}],
  'distance': 39,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True},
   {'id': '200-2000-0000', 'name': 'Nachtleben/Entertainment'},
   {'id': '200-2000-0011', 'name': 'Bar oder Pub'},
   {'id': '200-2000-0368', 'name': 'Cocktail Lounge'}],
  'references': [{'supplier': {'id': 'core'}, 'id': '1154509862'},
   {'supplier': {'id': 'tripadvisor'}, 'id': '2145871'},
   {'supplier': {'id': 'yelp'}, 'id': 'M4CY9JT4BYT4OMWfMZlXOg'}],
  'contacts': [{'phone': [{'value': '+493023890',
      'categories': [{'id': '100-1000-0000'},
       {'id': '200-2000-0000'},
       {'id': '200-2000-0011'}]},
     {'value': '+493023894249',
      'categories': [{'id': '100-1000-0000'}, {'id': '200-2000-0368'}]},
     {'value': '+493023894752', 'categories': [{'id': '100-1000-0000'}]},
     {'value': '+49493023890'}],
    'www': [{'value': 'http://www.spagos.de',
      'categories': [{'id': '100-1000-0000'},
       {'id': '200-2000-0000'},
       {'id': '200-2000-0011'}]}],
    'email': [{'value': 'berlin.hotel@rezidorparkinn.com',
      'categories': [{'id': '100-1000-0000'}, {'id': '200-2000-0011'}]}]}],
  'openingHours': [{'categories': [{'id': '200-2000-0368'}],
    'text': ['Mon-Sun: 06:00 - 01:00'],
    'isOpen': True,
    'structured': [{'start': 'T060000',
      'duration': 'PT19H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU'}]},
   {'categories': [{'id': '100-1000-0000'}, {'id': '200-2000-0011'}],
    'text': ['Mon-Sat: 00:00 - 01:00, 12:00 - 23:59',
     'Sun: 12:00 - 01:00, 12:00 - 23:59'],
    'isOpen': True,
    'structured': [{'start': 'T000000',
      'duration': 'PT01H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA'},
     {'start': 'T120000',
      'duration': 'PT11H59M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU'},
     {'start': 'T120000',
      'duration': 'PT13H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:SU'}]}]},
 {'title': "Humboldt's",
  'id': 'here:pds:place:276aabd1-213351f209f30e389f8607d313b91689',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': "Humboldt's, Alexanderplatz 7, 10178 Berlin, Deutschland",
   'district': 'Mitte',
   'street': 'Alexanderplatz',
   'postalCode': '10178',
   'houseNumber': '7'},
  'position': {'lat': 52.52255, 'lng': 13.4128},
  'access': [{'lat': 52.52249, 'lng': 13.41271}],
  'distance': 39,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True}],
  'references': [{'supplier': {'id': 'tripadvisor'}, 'id': '958783'},
   {'supplier': {'id': 'yelp'}, 'id': 'FeGToqSt105ySiyembGk5A'}],
  'foodTypes': [{'id': '300-000', 'name': 'Europäisch', 'primary': True},
   {'id': '800-064', 'name': 'International'}],
  'contacts': [{'phone': [{'value': '+493023890'},
     {'value': '+493023894646'},
     {'value': '+49493023890'}],
    'www': [{'value': 'http://www.parkinn-berlin.com/info-de.html'},
     {'value': 'https://www.parkinn-berlin.de/restaurant-humboldts'}]}],
  'openingHours': [{'text': ['Mon-Sun: 12:00 - 15:00, 18:00 - 22:30'],
    'isOpen': False,
    'structured': [{'start': 'T120000',
      'duration': 'PT03H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU'},
     {'start': 'T180000',
      'duration': 'PT04H30M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU'}]}]},
 {'title': 'Zur Wiesnwirtin',
  'id': 'here:pds:place:276u33dc-4369d23c2c84454d9d893660a175ca02',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'Zur Wiesnwirtin, Alexanderstraße, 10178 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Alexanderstraße',
   'postalCode': '10178'},
  'position': {'lat': 52.52291, 'lng': 13.41319},
  'access': [{'lat': 52.52309, 'lng': 13.41341}],
  'distance': 55,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True}],
  'contacts': [{'www': [{'value': 'http://www.zurwiesnwirtin.de'}]}]},
 {'title': 'Döner Inn',
  'id': 'here:pds:place:276u33dc-d70f980e8f364ddb9ded5966ab0ffbc2',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'Döner Inn, Alexanderplatz, 10178 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Alexanderplatz',
   'postalCode': '10178'},
  'position': {'lat': 52.52327, 'lng': 13.41159},
  'access': [{'lat': 52.52342, 'lng': 13.41237}],
  'distance': 76,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True},
   {'id': '100-1000-0009', 'name': 'Fastfood'}],
  'references': [{'supplier': {'id': 'tripadvisor'}, 'id': '4496377'},
   {'supplier': {'id': 'yelp'}, 'id': 'CnM6cwQctsMqyQB0l31htA'}],
  'foodTypes': [{'id': '250-000', 'name': 'Nahöstlich', 'primary': True},
   {'id': '252-000', 'name': 'Türkisch'}],
  'contacts': [{'phone': [{'value': '+4917620201328'}],
    'www': [{'value': 'https://www.doener-inn.de'}]}],
  'openingHours': [{'text': ['Mon-Sat: 00:00 - 02:00, 09:00 - 23:59',
     'Sun: 09:00 - 02:00, 09:00 - 23:59'],
    'isOpen': True,
    'structured': [{'start': 'T000000',
      'duration': 'PT02H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA'},
     {'start': 'T090000',
      'duration': 'PT14H59M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU'},
     {'start': 'T090000',
      'duration': 'PT17H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:SU'}]}]},
 {'title': 'DINEA Gastronomie',
  'id': 'here:pds:place:276u33dc-e6aedc926e744777b8bce488c4d822c6',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'DINEA Gastronomie, Alexanderplatz 9, 10178 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Alexanderplatz',
   'postalCode': '10178',
   'houseNumber': '9'},
  'position': {'lat': 52.52214, 'lng': 13.41203},
  'access': [{'lat': 52.52254, 'lng': 13.41261}],
  'distance': 78,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True}],
  'references': [{'supplier': {'id': 'core'}, 'id': '1222243524'}],
  'foodTypes': [{'id': '304-000', 'name': 'Italienisch', 'primary': True}],
  'contacts': [{'phone': [{'value': '+4930247430'}]}]},
 {'title': 'Sapori Italiani',
  'id': 'here:pds:place:276u33dc-746b3b2c9b484b7cb0c7edaa6dc02dd6',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'Sapori Italiani, Alexanderplatz 9, 10178 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Alexanderplatz',
   'postalCode': '10178',
   'houseNumber': '9'},
  'position': {'lat': 52.52214, 'lng': 13.41203},
  'access': [{'lat': 52.52254, 'lng': 13.41261}],
  'distance': 78,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True}],
  'references': [{'supplier': {'id': 'tripadvisor'}, 'id': '3434799'},
   {'supplier': {'id': 'yelp'}, 'id': 'M2na-OKI12Q88t1AYVYNpw'}],
  'foodTypes': [{'id': '304-000', 'name': 'Italienisch', 'primary': True},
   {'id': '300-000', 'name': 'Europäisch'},
   {'id': '372-000', 'name': 'Mediterran'},
   {'id': '800-057', 'name': 'Pizza'}],
  'contacts': [{'phone': [{'value': '+493028883189'}],
    'www': [{'value': 'http://saporiitaliani.foodpearl.com'},
     {'value': 'http://www.pizzeria-saporiitaliani.de',
      'categories': [{'id': '100-1000-0000'}]},
     {'value': 'https://www.facebook.com/SaporiFood',
      'categories': [{'id': '100-1000-0000'}]}]}]},
 {'title': 'BURGER KING',
  'id': 'here:pds:place:276u33dc-2ba407e1181849c9a761a336b8df1805',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'BURGER KING, Alexanderplatz 8, 10178 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Alexanderplatz',
   'postalCode': '10178',
   'houseNumber': '8'},
  'position': {'lat': 52.52226, 'lng': 13.41327},
  'access': [{'lat': 52.52218, 'lng': 13.41329}],
  'distance': 84,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True}],
  'chains': [{'id': '1498', 'name': 'BURGER KING'}],
  'references': [{'supplier': {'id': 'core'}, 'id': '1031172869'},
   {'supplier': {'id': 'core'}, 'id': '979355659'},
   {'supplier': {'id': 'tripadvisor'}, 'id': '5511033'},
   {'supplier': {'id': 'yelp'}, 'id': 'aRHVHLe934yXvTs6lr1ymw'}],
  'foodTypes': [{'id': '800-050', 'name': 'Fastfood', 'primary': True}],
  'contacts': [{'phone': [{'value': '+49302415672'},
     {'value': '+493024729825'},
     {'value': '+493028886030'},
     {'value': '+4949302415672'}],
    'www': [{'value': 'www.burgerking.de'}]}],
  'openingHours': [{'text': ['Mon-Sun: 00:00 - 24:00'],
    'isOpen': True,
    'structured': [{'start': 'T000000',
      'duration': 'PT24H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU'}]}]},
 {'title': 'Affengeil',
  'id': 'here:pds:place:276u33dc-bd01c881c4584d85a44c6b0021930707',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'Affengeil, Karl-Liebknecht-Straße, 10178 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Karl-Liebknecht-Straße',
   'postalCode': '10178'},
  'position': {'lat': 52.5234, 'lng': 13.4114},
  'access': [{'lat': 52.5234, 'lng': 13.4114}],
  'distance': 95,
  'categories': [{'id': '200-2000-0368',
    'name': 'Cocktail Lounge',
    'primary': True},
   {'id': '100-1000-0000', 'name': 'Restaurant'}],
  'references': [{'supplier': {'id': 'yelp'}, 'id': 'FqqtJ5RCOGTlkMwX8s9TRg'}],
  'foodTypes': [{'id': '800-060', 'name': 'Sandwiches', 'primary': True}]},
 {'title': 'Der Herr über die Grillkohle',
  'id': 'here:pds:place:276u33dc-516dd2b8385246b9bcf5c08b0f67b3df',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'Der Herr über die Grillkohle, Karl-Liebknecht-Straße, 10178 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Karl-Liebknecht-Straße',
   'postalCode': '10178'},
  'position': {'lat': 52.5235, 'lng': 13.4115},
  'access': [{'lat': 52.52348, 'lng': 13.41152}],
  'distance': 99,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True}],
  'references': [{'supplier': {'id': 'yelp'},
    'id': 'vRfyW24M_cDhSFNNRnlHPg'}]},
 {'title': 'Al Teatro',
  'id': 'here:pds:place:276u33dc-b197fa45c3f941a9b2d09b86bdc39c64',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'Al Teatro, Dircksenstraße 2, 10179 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Dircksenstraße',
   'postalCode': '10179',
   'houseNumber': '2'},
  'position': {'lat': 52.52196, 'lng': 13.41083},
  'access': [{'lat': 52.52209, 'lng': 13.4109}],
  'distance': 141,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True},
   {'id': '100-1100-0000', 'name': 'Kaffee/Tee'},
   {'id': '100-1100-0010', 'name': 'Kaffeehaus'},
   {'id': '600-6300-0064', 'name': 'Spezialitäten und Getränke'}],
  'references': [{'supplier': {'id': 'yelp'}, 'id': 'gi9yhyOoYHD6Wp-pKzrymg'}],
  'foodTypes': [{'id': '800-063', 'name': 'Eis', 'primary': True}],
  'contacts': [{'phone': [{'value': '+493024725336',
      'categories': [{'id': '100-1000-0000'}, {'id': '100-1100-0000'}]},
     {'value': '+493024781241'}],
    'www': [{'value': 'http://alteatro.de',
      'categories': [{'id': '100-1000-0000'}, {'id': '100-1100-0000'}]},
     {'value': 'https://alteatro-eismanufaktur.berlin/eiscafes-restaurants/bahnhof-alexanderplatz-berlin-mitte',
      'categories': [{'id': '100-1000-0000'}, {'id': '100-1000-0001'}]}]}],
  'openingHours': [{'categories': [{'id': '100-1000-0000'},
     {'id': '100-1100-0000'},
     {'id': '100-1100-0010'},
     {'id': '600-6300-0064'}],
    'text': ['Mon-Sun: 08:00 - 20:00'],
    'isOpen': True,
    'structured': [{'start': 'T080000',
      'duration': 'PT12H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU'}]}]},
 {'title': 'Currywurst Express',
  'id': 'here:pds:place:276u33dc-85ebd9b8d5db4c7bb7909468ff182e19',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'Currywurst Express, Dircksenstraße 2, 10179 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Dircksenstraße',
   'postalCode': '10179',
   'houseNumber': '2'},
  'position': {'lat': 52.52196, 'lng': 13.41083},
  'access': [{'lat': 52.52209, 'lng': 13.4109}],
  'distance': 141,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True},
   {'id': '100-1000-0009', 'name': 'Fastfood'}],
  'references': [{'supplier': {'id': 'tripadvisor'}, 'id': '4329136'},
   {'supplier': {'id': 'yelp'}, 'id': 'Bh_2d7VbkRMPlWTHnufMZg'}],
  'foodTypes': [{'id': '302-000', 'name': 'Deutsch', 'primary': True},
   {'id': '202-000', 'name': 'Indisch'},
   {'id': '800-078', 'name': 'Grillgerichte'}],
  'contacts': [{'phone': [{'value': '+493024720552'}],
    'www': [{'value': 'http://www.currywurstexpress.de',
      'categories': [{'id': '100-1000-0000'}]}]}],
  'openingHours': [{'categories': [{'id': '100-1000-0000'}],
    'text': ['Mon-Fri: 06:30 - 21:30', 'Sat, Sun: 08:00 - 21:30'],
    'isOpen': True,
    'structured': [{'start': 'T063000',
      'duration': 'PT15H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR'},
     {'start': 'T080000',
      'duration': 'PT13H30M',
      'recurrence': 'FREQ:DAILY;BYDAY:SA,SU'}]}]},
 {'title': 'Pergamon Döner&Pizza',
  'id': 'here:pds:place:276aabd1-81c26669d3bf0703666cb38c5fa3bdb0',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'Pergamon Döner&Pizza, Dircksenstraße 2, 10179 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Dircksenstraße',
   'postalCode': '10179',
   'houseNumber': '2'},
  'position': {'lat': 52.52196, 'lng': 13.41083},
  'access': [{'lat': 52.52209, 'lng': 13.4109}],
  'distance': 141,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True},
   {'id': '100-1000-0009', 'name': 'Fastfood'}],
  'references': [{'supplier': {'id': 'tripadvisor'}, 'id': '7366599'},
   {'supplier': {'id': 'yelp'}, 'id': '0QztYnqt1TebQ1MMjLsIwQ'}],
  'foodTypes': [{'id': '250-000', 'name': 'Nahöstlich', 'primary': True},
   {'id': '252-000', 'name': 'Türkisch'},
   {'id': '800-057', 'name': 'Pizza'}],
  'contacts': [{'phone': [{'value': '+491707767787'}],
    'www': [{'value': 'http://www.pergamongrill.de'}],
    'email': [{'value': 'akpolatneuzat@hotmail.com',
      'categories': [{'id': '100-1000-0000'}]}]}],
  'openingHours': [{'categories': [{'id': '100-1000-0000'}],
    'text': ['Mon-Fri: 10:00 - 03:00',
     'Sat, Sun: 04:00 - 06:00, 10:00 - 04:00'],
    'isOpen': True,
    'structured': [{'start': 'T100000',
      'duration': 'PT17H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR'},
     {'start': 'T040000',
      'duration': 'PT02H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:SA'},
     {'start': 'T100000',
      'duration': 'PT20H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:SA'},
     {'start': 'T100000',
      'duration': 'PT18H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:SU'}]},
   {'categories': [{'id': '100-1000-0009'}],
    'text': ['Mon-Thu: 00:00 - 05:00, 09:00 - 23:59',
     'Fri, Sat: 00:00 - 06:00, 10:00 - 23:59',
     'Sun: 09:00 - 05:00, 09:00 - 23:59'],
    'isOpen': True,
    'structured': [{'start': 'T000000',
      'duration': 'PT05H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH'},
     {'start': 'T090000',
      'duration': 'PT14H59M',
      'recurrence': 'FREQ:DAILY;BYDAY:MO,TU,WE,TH,SU'},
     {'start': 'T000000',
      'duration': 'PT06H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:FR,SA'},
     {'start': 'T100000',
      'duration': 'PT13H59M',
      'recurrence': 'FREQ:DAILY;BYDAY:FR,SA'},
     {'start': 'T090000',
      'duration': 'PT20H00M',
      'recurrence': 'FREQ:DAILY;BYDAY:SU'}]}]},
 {'title': 'Dinea Restaurant Berlin',
  'id': 'here:pds:place:276u33dc-a7024d8caa33408ba94bae28288f8269',
  'ontologyId': 'here:cm:ontology:restaurant',
  'resultType': 'place',
  'address': {'label': 'Dinea Restaurant Berlin, Stadtbahnbogen, 10179 Berlin, Deutschland',
   'district': 'Mitte',
   'street': 'Stadtbahnbogen',
   'postalCode': '10179'},
  'position': {'lat': 52.52176, 'lng': 13.41094},
  'access': [{'lat': 52.52194, 'lng': 13.41119}],
  'distance': 152,
  'categories': [{'id': '100-1000-0000',
    'name': 'Restaurant',
    'primary': True},
   {'id': '100-1000-0009', 'name': 'Fastfood'},
   {'id': '100-1100-0000', 'name': 'Kaffee/Tee'},
   {'id': '600-6900-0000', 'name': 'Konsumgüter'}],
  'references': [{'supplier': {'id': 'tripadvisor'}, 'id': '1889541'},
   {'supplier': {'id': 'yelp'}, 'id': 'HoFsCv-xobzSkq1b9xd9Ww'}],
  'foodTypes': [{'id': '300-000', 'name': 'Europäisch', 'primary': True},
   {'id': '302-000', 'name': 'Deutsch'},
   {'id': '800-050', 'name': 'Fastfood'},
   {'id': '800-064', 'name': 'International'}],
  'contacts': [{'phone': [{'value': '+493024743327',
      'categories': [{'id': '100-1000-0000'}]},
     {'value': '+493024743551', 'categories': [{'id': '100-1000-0000'}]},
     {'value': '+493024743748'},
     {'value': '+49493024743', 'categories': [{'id': '100-1000-0000'}]},
     {'value': '+4949302478546',
      'categories': [{'id': '100-1000-0000'}, {'id': '600-6900-0000'}]}],
    'fax': [{'value': '030 24743322',
      'categories': [{'id': '100-1000-0000'}]}],
    'www': [{'value': 'http://www.dinea-gruppe.de/index.php?&dinea_location=37',
      'categories': [{'id': '100-1000-0000'}]},
     {'value': 'http://www.dinea.de',

In [8]:
df = pd.DataFrame.from_dict(first_fetch)
df_ = df.drop(['id','ontologyId','resultType', 'references', 'contacts', 'access','categories'], axis=1)
df_.head()

,title,address,position,distance,foodTypes,openingHours,chains
0,Zillestube,"{'label': 'Zillestube, Alexanderplatz, 10178 B...","{'lat': 52.52289, 'lng': 13.41263}",19,"[{'id': '300-000', 'name': 'Europäisch', 'prim...","[{'categories': [{'id': '500-5000-0000'}], 'te...",NaN
1,Spagos,"{'label': 'Spagos, Alexanderplatz 7, 10178 Ber...","{'lat': 52.52255, 'lng': 13.4128}",39,NaN,"[{'categories': [{'id': '200-2000-0368'}], 'te...",NaN
2,Humboldt's,"{'label': 'Humboldt's, Alexanderplatz 7, 10178...","{'lat': 52.52255, 'lng': 13.4128}",39,"[{'id': '300-000', 'name': 'Europäisch', 'prim...","[{'text': ['Mon-Sun: 12:00 - 15:00, 18:00 - 22...",NaN
3,Zur Wiesnwirtin,"{'label': 'Zur Wiesnwirtin, Alexanderstraße, 1...","{'lat': 52.52291, 'lng': 13.41319}",55,NaN,NaN,NaN
4,Döner Inn,"{'label': 'Döner Inn, Alexanderplatz, 10178 Be...","{'lat': 52.52327, 'lng': 13.41159}",76,"[{'id': '250-000', 'name': 'Nahöstlich', 'prim...","[{'text': ['Mon-Sat: 00:00 - 02:00, 09:00 - 23...",NaN

In [9]:
df_.isna().sum()

title            0
address          0
position         0
distance         0
foodTypes       27
openingHours    33
chains          87
dtype: int64

In [10]:
# separate lat and lon

lat = []
lon = []

for items in first_fetch:
    lat.append(items['position']['lat'])
    lon.append(items['position']['lng'])
    
df_['lat'] = lat
df_['lon'] = lon
df_.drop(['position'], axis = 1)

,title,address,distance,foodTypes,openingHours,chains,lat,lon
0,Zillestube,"{'label': 'Zillestube, Alexanderplatz, 10178 B...",19,"[{'id': '300-000', 'name': 'Europäisch', 'prim...","[{'categories': [{'id': '500-5000-0000'}], 'te...",NaN,52.52289,13.41263
1,Spagos,"{'label': 'Spagos, Alexanderplatz 7, 10178 Ber...",39,NaN,"[{'categories': [{'id': '200-2000-0368'}], 'te...",NaN,52.52255,13.41280
2,Humboldt's,"{'label': 'Humboldt's, Alexanderplatz 7, 10178...",39,"[{'id': '300-000', 'name': 'Europäisch', 'prim...","[{'text': ['Mon-Sun: 12:00 - 15:00, 18:00 - 22...",NaN,52.52255,13.41280
3,Zur Wiesnwirtin,"{'label': 'Zur Wiesnwirtin, Alexanderstraße, 1...",55,NaN,NaN,NaN,52.52291,13.41319
4,Döner Inn,"{'label': 'Döner Inn, Alexanderplatz, 10178 Be...",76,"[{'id': '250-000', 'name': 'Nahöstlich', 'prim...","[{'text': ['Mon-Sat: 00:00 - 02:00, 09:00 - 23...",NaN,52.52327,13.41159
...,...,...,...,...,...,...,...,...
95,The Reed,"{'label': 'The Reed, Karl-Liebknecht-Straße 13...",296,"[{'id': '300-000', 'name': 'Europäisch', 'prim...","[{'categories': [{'id': '100-1000-0000'}], 'te...",NaN,52.52234,13.40809
96,Brauhaus Lemke am Alex,"{'label': 'Brauhaus Lemke am Alex, Karl-Liebkn...",296,"[{'id': '302-000', 'name': 'Deutsch', 'primary...","[{'categories': [{'id': '300-3000-0350'}], 'te...",NaN,52.52234,13.40809
97,Phoenix,"{'label': 'Phoenix, Karl-Liebknecht-Straße 13,...",296,"[{'id': '200-000', 'name': 'Asiatisch', 'prima...",NaN,NaN,52.52234,13.40809
98,Aga Kebab-Restaurant,"{'label': 'Aga Kebab-Restaurant, Karl-Liebknec...",298,"[{'id': '252-000', 'name': 'Türkisch', 'primar...",NaN,NaN,52.52155,13.40851
99,Café Oliv,"{'label': 'Café Oliv, Münzstraße 8, 10178 Berl...",307,"[{'id': '300-000', 'name': 'Europäisch', 'prim...","[{'categories': [{'id': '100-1000-0001'}, {'id...",NaN,52.52438,13.40868

In [11]:
# separate full address

full_address = []
district = []

for items in first_fetch:
    full_address.append(items['address']['label'])
    district.append(items['address']['district'])
    
df_['full_address'] = full_address 
df_['district'] = district

In [12]:
street = []

# separate street name

for items in first_fetch:
    try:
        street.append(items['address']['street'])
    except:
        street.append('NaN')
    
df_['street'] = street

In [13]:
# separate house number

house_nr = []

for items in first_fetch:
    try:
        house_nr.append(items['address']['houseNumber'])
    except:
        house_nr.append('NaN')
        
df_['house_nr'] = house_nr

In [14]:
# separate zipcode

zip_code = []

for items in first_fetch:
    try:
        zip_code.append(items['address']['postalCode'])
    except:
        zip_code.append('NaN')


df_['zip_code'] = zip_code

In [15]:
# get food types

cuisine_general = []

for items in first_fetch:
    try:
        cuisine_general.append(items['foodTypes'][0]['name'])
    except:
        cuisine_general.append('NaN')


df_['cuisine_general'] = cuisine_general

In [16]:
# get food types detail
cuisine_detail = []

for items in first_fetch:
    try:
        cuisine_detail.append(items['foodTypes'][1]['name'])
    except:
        cuisine_detail.append('NaN')

df_['cuisine_detail'] = cuisine_detail

In [17]:
# get opening hours

opening_hours = []

for items in first_fetch:
    try:
        opening_hours.append(items['openingHours'][0]['text'][0])
    except:
        opening_hours.append('NaN')

df_['opening_hours'] = opening_hours

In [18]:
# drop useless columns

final_df = df_.drop(['foodTypes','position','address','openingHours'],axis = 1)

In [19]:
# rename the restaurant name
final_df = final_df.rename(columns={"title": 'restaurant_name'})

In [20]:
final_df.head()

,restaurant_name,distance,chains,lat,lon,full_address,district,street,house_nr,zip_code,cuisine_general,cuisine_detail,opening_hours
0,Zillestube,19,NaN,52.52289,13.41263,"Zillestube, Alexanderplatz, 10178 Berlin, Deut...",Mitte,Alexanderplatz,NaN,10178,Europäisch,Deutsch,Mon-Sun: 17:30 - 23:00
1,Spagos,39,NaN,52.52255,13.41280,"Spagos, Alexanderplatz 7, 10178 Berlin, Deutsc...",Mitte,Alexanderplatz,7,10178,NaN,NaN,Mon-Sun: 06:00 - 01:00
2,Humboldt's,39,NaN,52.52255,13.41280,"Humboldt's, Alexanderplatz 7, 10178 Berlin, De...",Mitte,Alexanderplatz,7,10178,Europäisch,International,"Mon-Sun: 12:00 - 15:00, 18:00 - 22:30"
3,Zur Wiesnwirtin,55,NaN,52.52291,13.41319,"Zur Wiesnwirtin, Alexanderstraße, 10178 Berlin...",Mitte,Alexanderstraße,NaN,10178,NaN,NaN,NaN
4,Döner Inn,76,NaN,52.52327,13.41159,"Döner Inn, Alexanderplatz, 10178 Berlin, Deuts...",Mitte,Alexanderplatz,NaN,10178,Nahöstlich,Türkisch,"Mon-Sat: 00:00 - 02:00, 09:00 - 23:59"

In [35]:
final_df.columns

Index(['restaurant_name', 'distance', 'chains', 'lat', 'lon', 'full_address',
       'district', 'street', 'house_nr', 'zip_code', 'cuisine_general',
       'cuisine_detail', 'opening_hours'],
      dtype='object')

In [36]:
# null counts

final_df['cuisine_general'].value_counts()
final_df['cuisine_detail'].value_counts()

NaN                         52
Deutsch                      7
Europäisch                   7
Asiatisch                    6
Pizza                        3
Chinesisch                   3
Amerikanisch - Barbecue      2
Indisch                      2
Türkisch                     2
Sandwiches                   2
Amerikanisch                 2
Mexikanisch                  2
Japanisch - Sushi            2
Fisch und Meeresfrüchte      1
International                1
Griechisch                   1
Vietnamesisch                1
Snacks und Getränke          1
Frühstück                    1
Fastfood                     1
Amerikanisch - Soul Food     1
Name: cuisine_detail, dtype: int64

In [38]:
final_df['restaurant_name'].unique()

array(['Zillestube', 'Spagos', "Humboldt's", 'Zur Wiesnwirtin',
       'Döner Inn', 'DINEA Gastronomie', 'Sapori Italiani', 'BURGER KING',
       'Affengeil', 'Der Herr über die Grillkohle', 'Al Teatro',
       'Currywurst Express', 'Pergamon Döner&Pizza',
       'Dinea Restaurant Berlin', 'Café Röntgen', 'Braufactum',
       'Mama van', "John's Burgerladen", 'SUBWAY', 'Fish&Chips',
       'Thanglong Asia', "L'Osteria Berlin Memhardstraße", 'Romantica',
       "Linh's Asian Restaurant", 'Alex Lunch', 'Cantino', 'Anan',
       'Chopstix', 'Pezzo di Pizza', 'Thang Long Asia Food', 'Spreegold',
       'Coffee Fellows', 'Mio - Icecream and Snacks',
       'Ssi am Alex Institut für Tourismus und Marketing', 'Alex Berlin',
       'Manga Matsuri', 'Escados', 'Sodexo Restaurant', 'Eat Berlin',
       "Gregory's", 'Berliner Marcus Bräu',
       'TV- Turm Alexanderplatz Gastronomiegesellschaft', 'Pan-M Gastro',
       'Good Bank', "Brammibal's Donuts", 'Esra Falafel', 'Bibi Mix',
       'Madami', 'Angry Chicken', 'Wok to Walk', 'Soupkultur',
       'Microbrauerei Barkowsky', 'Dolores', 'Katharina Körner',
       'Besenkammer', 'Alex Berlin Alexanderplatz', 'Hofbräu Berlin',
       'KFC', 'Prince', 'Restaurant Café Luchs', "Bell' Chicco",
       'Absolutwind', 'Prince 27', 'Don Angelo', 'Momotaro Tavern',
       'Der Alte Fritz', 'Schmankerl Hüttn', 'Asiagourmet', 'Scoom',
       'Kentucky Fried Chicken', 'Nudelbox', 'Five Guys', 'Com Viet',
       'VAPIANO', 'La Luna', 'Vincenzo', 'Carambar', 'Alex Döner & Pizza',
       'Olle Bolle', 'H2-Hub', 'Steaks & more RAMADA',
       'Restaurant Berlin', 'Thai Inside', 'Berliner Fernsehturm',
       'Ho Vang', 'King King', 'Sphere Restaurant',
       'Le Hung-Fresh Asian F.', 'Alex Bistro Berlin-Mitte',
       'Ristorante Palermo', 'The Reed', 'Brauhaus Lemke am Alex',
       'Phoenix', 'Aga Kebab-Restaurant', 'Café Oliv'], dtype=object)

## QUERY WITH ALL COORDINATES

In [69]:
# loads CSV file into a DF

list_coordinates = pd.read_csv('/Users/support/code/ClaireLa/next_restaurant/Berlin_coordinates.csv')
list_coordinates

              lat        lng
0       52.338234  13.088346
1       52.339136  13.088346
2       52.340037  13.088346
3       52.340939  13.088346
4       52.341841  13.088346
...           ...        ...
170245  52.671848  13.761117
170246  52.672749  13.761117
170247  52.673651  13.761117
170248  52.674553  13.761117
170249  52.675454  13.761117

[170250 rows x 2 columns]

In [73]:
list_coordinates

              lat        lng
0       52.338234  13.088346
1       52.339136  13.088346
2       52.340037  13.088346
3       52.340939  13.088346
4       52.341841  13.088346
...           ...        ...
170245  52.671848  13.761117
170246  52.672749  13.761117
170247  52.673651  13.761117
170248  52.674553  13.761117
170249  52.675454  13.761117

[170250 rows x 2 columns]

In [77]:
# Call the API --- I stopped at 151 files yesterday


for index in range(len(list_coordinates)):
    
    query = fetch_here(list_coordinates['lat'][index],
                       list_coordinates['lng'][index],
                       'e8Jr90z14vvM6WedTBedm2Trnv4J_-KLqH4vVllGqqI')
    
    # first cleaning
    
    dataframe = pd.DataFrame.from_dict(query)
    dataframe_ = dataframe.drop(['id','ontologyId','resultType', 'references', 'contacts', 'access','categories'], axis=1)

    # Save into csv file
    
    dataframe_.to_csv(f'/Users/support/code/ClaireLa/next_restaurant/here_query_{index}.csv')

KeyboardInterrupt:

In [74]:
# Call the API


for index in range(len(list_coordinates)):
    
    query = fetch_here(list_coordinates['lat'][index],
                       list_coordinates['lng'][index],
                       'e8Jr90z14vvM6WedTBedm2Trnv4J_-KLqH4vVllGqqI')
   

    lat = []
    lon = []
    full_address = []
    district = []
    street = []
    house_nr = []
    zip_code = []
    cuisine_general = []
    cuisine_detail = []
    opening_hours = []

    # Clean the data

    for restaurant in query:
        for item in to_delete_1:
            del restaurant['address'][item]
            
    dataframe = pd.DataFrame.from_dict(query)
    dataframe_ = dataframe.drop(['id','ontologyId','resultType', 'references', 'contacts', 'access','categories'], axis=1)

    # separate lat and lon
    
    for items in query:
        lat.append(items['position']['lat'])
        lon.append(items['position']['lng'])
    
    dataframe_['lat'] = lat
    dataframe_['lon'] = lon
    dataframe_.drop(['position'], axis = 1)
    
    # separate full address

    for items in query:
        full_address.append(items['address']['label'])
        district.append(items['address']['district'])

    dataframe_['full_address'] = full_address 
    dataframe_['district'] = district
    
    # separate street name

    for items in query:
        try:
            street.append(items['address']['street'])
        except:
            street.append('NaN')

    dataframe_['street'] = street
    
    
    # separate house number

    for items in query:
        try:
            house_nr.append(items['address']['houseNumber'])
        except:
            house_nr.append('NaN')

    dataframe_['house_nr'] = house_nr
    
    # separate zipcode

    for items in query:
        try:
            zip_code.append(items['address']['postalCode'])
        except:
            zip_code.append('NaN')


    dataframe_['zip_code'] = zip_code
    
    
    # get food types

    for items in query:
        try:
            cuisine_general.append(items['foodTypes'][0]['name'])
        except:
            cuisine_general.append('NaN')

    dataframe_['cuisine_general'] = cuisine_general
    
    # get food types detail

    for items in query:
        try:
            cuisine_detail.append(items['foodTypes'][1]['name'])
        except:
            cuisine_detail.append('NaN')

    dataframe_['cuisine_detail'] = cuisine_detail
    
    # get opening hours

    for items in query:
        try:
            opening_hours.append(items['openingHours'][0]['text'][0])
        except:
            opening_hours.append('NaN')

    dataframe_['opening_hours'] = opening_hours
    
    # drop useless columns

    final_dataframe = dataframe_.drop(['foodTypes','position','address','openingHours'],axis = 1)

    # rename the restaurant name
    
    final_dataframe = final_dataframe.rename(columns={"title": 'restaurant_name'})
    
    # Save into csv file
    
    final_dataframe.to_csv(f'/Users/support/code/ClaireLa/next_restaurant/here_query{_index}.csv')

KeyError: 'district'

In [15]:
# generate a list of coordinates within 10 km around the center of Berlin


list_coordinates_with_distance = pd.read_csv('/Users/support/code/ClaireLa/next_restaurant/coordinates_list/Berlin_coordinates_with_distances.csv')

list_coordinates_with_distance = list_coordinates_with_distance.reset_index()
ten_k = list_coordinates_with_distance[list_coordinates_with_distance['distance'] < 10]
ten_k.sort_values(by = 'distance')

ten_k.to_csv(f'/Users/support/code/ClaireLa/next_restaurant/coordinates_list/ten_kilometers.csv')

In [ ]:

# Call the API --- I stopped at 151 files yesterday


for index in range(len(list_coordinates)):
    
    query = fetch_here(list_coordinates['lat'][index],
                       list_coordinates['lng'][index],
                       'e8Jr90z14vvM6WedTBedm2Trnv4J_-KLqH4vVllGqqI')
    
    # first cleaning
    
    dataframe = pd.DataFrame.from_dict(query)
    dataframe_ = dataframe.drop(['id','ontologyId','resultType', 'references', 'contacts', 'access','categories'], axis=1)

    # Save into csv file
    
    dataframe_.to_csv(f'/Users/support/code/ClaireLa/next_restaurant/here_query_{index}.csv')

In [31]:
# concatenate CSV files 

import glob
import pandas as pd

df = pd.concat(map(pd.read_csv, glob.glob('../here_query_first_trial/*.csv')))

In [32]:
# check shape, drop duplicates and check shape again
df.shape

df = df.drop_duplicates(subset=['title'])

df.shape

(15200, 8)

## Call API on ten kilometers around the center of Berlin

In [ ]:
# Call the API


for i in range(len(ten_k)):
    
    query = fetch_here(ten_k.lat.iloc[i],
                       ten_k.lng.iloc[i],
                       'e8Jr90z14vvM6WedTBedm2Trnv4J_-KLqH4vVllGqqI')
    
    # first cleaning
    
    dataframe = pd.DataFrame.from_dict(query)
    #dataframe_ = dataframe.drop(['id','ontologyId','resultType', 'references', 'contacts', 'access','categories'], axis=1)

    
    # get index
    
    index = ten_k.iloc[i]['index']
    
    # Save into csv file
    
    dataframe.to_csv(f'/Users/support/code/ClaireLa/next_restaurant/here_query_ten_k/here_query_{index}.csv')